import type { Metadata } from "next";
import Header from "@/components/header/top-header";
import Footer from "@/components/footer";
import "./globals.css";
import BottomHeader from "@/components/header/bottom-header";
import CartProvider from "@/redux/CartProvider";
import AuthProvider from "@/components/provider/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


async function getData() {
  const res = await fetch("https://fakestoreapiserver.reactbd.com/tech");
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  
  const data = await getData();
  
  
  return (
    <html lang='en'>
      <body>
        <CartProvider>
          <AuthProvider>
            <Header getData={data} />
            <BottomHeader />
            {children}
            <Footer />
          </AuthProvider>
        </CartProvider>
      </body>
    </html>
  );
}
